[package]
name = "crates-fcgi"
version = "0.1.0"
authors = ["lightsing <light.tsing@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
bytes = "0.6"
hyper = "0.13"
hyper-tls = "0.4"
http-body = "0.3"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
lazy_static = "1.4"