refresh_rate: 30 seconds
appenders:
  stdout-lineno:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l:<5} [{T}] {M}(({f}:{L})): {m}{n}"
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l:<5} [{T}] {M}((...)): {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  crates_io_cn:
    level: debug
    additive: false
    appenders:
      - stdout-lineno